Coverage for Repository.Person.equals()
DD2480-Project-group-25/java-design-patterns pull request #35
Opened 2019-02-17 14:59 UTC by vronc

Add coverage tool for equals-method in class Person (used in _Repository_).

2019-02-17 15:33 UTC, helenaalinder requested changes

2019-02-17 15:33 UTC, helenaalinder commented on repository/src/main/java/com/iluwatar/repository/Person.java
>    }
You can instantiate this directly after private boolean[] localCoveredBranches and set every element to false in a BeforeEach or an AfterEach in the testclass

2019-02-17 17:08 UTC, helenaalinder approved these changes

2019-02-17 17:08 UTC, merged

2019-02-18 09:49 UTC, vronc commented
Fix #16