Add tests for 100% coverage of Repository.Person.equals() - Fix #17
DD2480-Project-group-25/java-design-patterns pull request #36
Opened 2019-02-17 16:01 UTC by vronc

Add tests to RepositoryTest to improve coverage on method Person.equals.

Previously tested requirements of Person.equals() (Coverage 24%) :
- Comparision of age.
- Positive instance, when compared objects are equal.
 Previously untested but now tested requirements of Person.equals() (Coverage 100%):
- Positive instances:
    - Compare object to self.
    - Compare equal objects that don't have first names or surnames.
- Negative instances:
    - Compare non-equal first names, surnames and id's.
    - Compare if one Person-object's first name, surname or id is null.
    - If input object is null.
    - If the input object is not of class Person.

2019-02-17 18:12 UTC, alzahraasalman requested changes

2019-02-17 18:12 UTC, alzahraasalman commented on repository/src/test/java/com/iluwatar/repository/RepositoryTest.java
> +  }
This test should be divided to 3 different tests with one asserTrue each

2019-02-17 18:13 UTC, alzahraasalman requested changes

2019-02-17 18:13 UTC, alzahraasalman commented on repository/src/test/java/com/iluwatar/repository/RepositoryTest.java
> +
Same here, split into several tests :)

2019-02-18 08:26 UTC, alzahraasalman approved these changes
Looks good!

2019-02-18 08:26 UTC, merged

2019-02-18 09:48 UTC, vronc commented
Fix #17